#
# Makefile for the nubia drivers.
#
obj-$(CONFIG_NUBIA_FINGERPRINT)                   += fingerprint/
obj-$(CONFIG_NUBIA_TOUCH)                         += touch/
obj-$(CONFIG_NUBIA_CYPRESS_KEYBOARD_GAMEFIRE) += cy8c4014l_touchkey/
