ccflags-y += -Idrivers/media/platform/msm/camera_nubia/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_nubia/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_nubia/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_nubia/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_nubia/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/camera_nubia/cam_cdm
ccflags-y += -Idrivers/media/platform/msm/camera_nubia/cam_fd
ccflags-y += -Idrivers/media/platform/msm/camera_nubia/cam_fd/fd_hw_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_nubia/cam_fd/fd_hw_mgr/fd_hw
ccflags-y += -Idrivers/media/platform/msm/camera_nubia
ccflags-y += -Idrivers/media/platform/msm/camera_nubia/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += cam_fd_hw_dev.o cam_fd_hw_core.o cam_fd_hw_soc.o
